# Generated by Django 4.0.6 on 2022-08-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcafe', '0002_alter_menu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('お店の紹介', 'お店の紹介'), ('期間限定メニュー', '期間限定メニュー'), ('イベント', 'イベント'), ('お客様との会話', 'お客様との会話')], max_length=100, verbose_name='カテゴリー'),
        ),
    ]
